using System.Collections.Generic;

namespace Modules.FreverUMA
{
    internal static class UMABodyPartMapping
    {
        public static readonly Dictionary<UMABodyPart, string> BODY_PART_MAPPING = new Dictionary<UMABodyPart, string>()
        {
            {UMABodyPart.Weight, "weight"},
            {UMABodyPart.Muscle, "muscle"},
            {UMABodyPart.GluteSize, "gluteSize"},
            {UMABodyPart.HipSize, "hipSize"},
            {UMABodyPart.ThighThickness, "thighThickness"},
            {UMABodyPart.CalfThickness, "calfThickness"},
            {UMABodyPart.BellySize, "bellySize"},
            {UMABodyPart.NeckSize, "neckSize"},
            {UMABodyPart.WaistSize, "waist Size"},
            {UMABodyPart.TrapeziusSize, "trapeziusSize"},
            {UMABodyPart.ShoulderSize, "shoulderSize"},
            {UMABodyPart.ArmThickness, "arm Thickness"},
            {UMABodyPart.ForearmThickness, "forearmThickness"},
            {UMABodyPart.RibcageSize, "ribcageSize"},
            {UMABodyPart.ChestSize, "chestSize"},
            {UMABodyPart.BreastSize, "breastSize"},
            {UMABodyPart.EyeSize, "eyeSize"},
            {UMABodyPart.EyePosition, "eyePosition"},
            {UMABodyPart.EyeWidth, "eyeWidth"},
            {UMABodyPart.EyeRotate, "eyeRotate"},
            {UMABodyPart.EyeSizeWidth, "eyeSizeWidth"},
            {UMABodyPart.EyeLowerlid, "eyeLowerlid"},
            {UMABodyPart.EyeUpperlid, "eyeUpperlid"},
            {UMABodyPart.Monolid, "monolid"},
            {UMABodyPart.Creasedlid, "creasedlid"},
            {UMABodyPart.Doublelid, "doublelid"},
            {UMABodyPart.EyeUpperlidInnerVertical, "eyeUpperlidInnerVertical"},
            {UMABodyPart.EyeUpperlidInnerHorizontal, "eyeUpperlidInnerHorizontal"},
            {UMABodyPart.EyeUpperlidMidVertical, "eyeUpperlidMidVertical"},
            {UMABodyPart.EyeUpperlidMidHorizontal, "eyeUpperlidMidHorizontal"},
            {UMABodyPart.EyeUpperlidOuterVertical, "eyeUpperlidOuterVertical"},
            {UMABodyPart.EyeUpperlidOuterHorizontal, "eyeUpperlidOuterHorizontal"},
            {UMABodyPart.EyeLowerlidInnerVertical, "eyeLowerlidInnerVertical"},
            {UMABodyPart.EyeLowerlidInnerHorizontal, "eyeLowerlidInnerHorizontal"},
            {UMABodyPart.EyeLowerlidMidVertical, "eyeLowerlidMidVertical"},
            {UMABodyPart.EyeLowerlidMidHorizontal, "eyeLowerlidMidHorizontal"},
            {UMABodyPart.EyeLowerlidOuterVertical, "eyeLowerlidOuterVertical"},
            {UMABodyPart.EyeLowerlidOuterHorizontal, "eyeLowerlidOuterHorizontal"},
            {UMABodyPart.EyeInner, "eyeInner"},
            {UMABodyPart.EyeOuter, "eyeOuter"},
            {UMABodyPart.CheekSize, "cheek Size"},
            {UMABodyPart.CheekBoneSize, "cheekBone Size"},
            {UMABodyPart.EarSize, "ear Size"},
            {UMABodyPart.ChinLength, "chinLength"},
            {UMABodyPart.ChinHeigth, "chinHeigth"},
            {UMABodyPart.ChinWidth, "chinWidth"},
            {UMABodyPart.JawLength, "jawLength"},
            {UMABodyPart.JawSize, "jawSize"},
            {UMABodyPart.JawWidth, "jawWidth"},
            {UMABodyPart.Jawline, "jawline"},
            {UMABodyPart.FaceWidth, "faceWidth"},
            {UMABodyPart.FaceHeigth, "faceHeigth"},
            {UMABodyPart.HeadSize, "headSize"},
            {UMABodyPart.EarPosition, "earPosition"},
            {UMABodyPart.MouthSize, "mouthSize"},
            {UMABodyPart.MouthUpperlipSize, "mouthUpperlipSize"},
            {UMABodyPart.MouthLowerlipSize, "mouthLowerlipSize"},
            {UMABodyPart.MouthCorners, "mouthCorners"},
            {UMABodyPart.MouthPosition, "mouthPosition"},
            {UMABodyPart.MouthCupidbow, "mouthCupidbow"},
            {UMABodyPart.MouthCupidbowAdjust, "mouthCupidbowAdjust"},
            {UMABodyPart.MouthTeardrop, "mouthTeardrop"},
            {UMABodyPart.MouthTeardropAdjust, "mouthTeardropAdjust"},
            {UMABodyPart.MouthCornersVertical, "mouthCornersVertical"},
            {UMABodyPart.NoseSize, "noseSize"},
            {UMABodyPart.NosePosition, "nosePosition"},
            {UMABodyPart.NoseWidth, "noseWidth"},
            {UMABodyPart.NoseLength, "noseLength"},
            {UMABodyPart.NoseTipLength, "noseTipLength"},
            {UMABodyPart.NoseTipSize, "nose TipSize"},
            {UMABodyPart.NoseWingWidth, "nose WingWidth"},
            {UMABodyPart.NoseWingPosition, "noseWingPosition"},
            {UMABodyPart.NoseTipRotate, "noseTipRotate"},
            {UMABodyPart.EyebrowSize, "eyebrowSize"},
            {UMABodyPart.EyebrowThickness, "eyebrowThickness"},
            {UMABodyPart.EyebrowRotate, "eyebrowRotate"},
            {UMABodyPart.EyebrowPosition, "eyebrowPosition"}
        };
    }
}


